version: '3.1'
services:
  vidtunnel-redis:
      restart: unless-stopped
      image: rabbitmq:3.7.13-management-alpine
      container_name: vidtunnel-redis
      environment:
        RABBITMQ_DEFAULT_USER: rabbitmq
        RABBITMQ_DEFAULT_PASS: helloworld
        RABBITMQ_DEFAULT_VHOST: /
      ports:
          - '15672:15672'
          - '5672:5672'
